[package]
name = "bambam-gbfs"
version = "0.2.2"
edition = "2024"

[dependencies]
routee-compass-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
geo = { workspace = true }
reqwest = { workspace = true }