[algorithm]
type = "a*"

[cost.vehicle_rates.trip_time]
type = "raw"

[cost.weights]
trip_time = 1.0

[label]
max_trip_legs = 5
modes = [
    "walk",
    "transit",
]
type = "multimodal"

[mapping]
matching_type = [
    "point",
    "vertex_id",
    "edge_id",
]
queries_without_destinations = false

[mapping.tolerance]
distance = 15.0
unit = "meters"

[[mapping.geometry]]
type = "from_linestrings"
geometry_input_file = "boulder_co/edges-geometries-enumerated.txt.gz"

[[mapping.geometry]]
type = "from_linestrings"
geometry_input_file = "boulder_co/transit/edges-geometries-enumerated-1.txt.gz"

[graph]
vertex_list_input_file = "boulder_co/vertices-compass.csv.gz"

[[graph.edge_list]]
input_file = "boulder_co/edges-compass.csv.gz"

[[graph.edge_list]]
input_file = "boulder_co/transit/edges-compass-1.csv.gz"

[[search]]

[search.traversal]
type = "combined"

[[search.traversal.models]]
distance_unit = "miles"
type = "distance"

[[search.traversal.models]]
name = "walk"
speed = 5.0
speed_unit = "kph"
type = "fixed_speed"

[[search.traversal.models]]
time_unit = "minutes"
type = "time"

[[search.traversal.models]]
available_modes = [
    "walk",
    "transit",
]
available_route_ids = []
max_trip_legs = 5
this_mode = "walk"
type = "multimodal"
use_route_ids = false

[search.frontier]
type = "combined"

[[search.frontier.models]]
type = "time_limit"

[search.frontier.models.time_limit]
time = 40.0
time_unit = "minutes"

[[search.frontier.models]]
available_modes = [
    "walk",
    "transit",
]
available_route_ids = []
constraints = []
max_trip_legs = 5
this_mode = "walk"
type = "multimodal"
use_route_ids = false

[[search]]

[search.traversal]
type = "combined"

[[search.traversal.models]]
type = "distance"
distance_unit = "miles"

[[search.traversal.models]]
type = "transit"
edges_schedules_input_file = "boulder_co/transit/edges-schedules-1.csv.gz"
gtfs_metadata_input_file = "boulder_co/transit/edges-gtfs-metadata-1.json"
route_ids_input_file = "boulder_co/transit/fq-route-ids-enumerated.txt.gz"
schedule_loading_policy = "All"

[[search.traversal.models]]
type = "multimodal"
this_mode = "transit"
available_modes = [
    "walk",
    "transit",
]
route_ids_input_file = "boulder_co/transit/fq-route-ids-enumerated.txt.gz"
max_trip_legs = 5

[search.frontier]
type = "combined"

[[search.frontier.models]]
type = "time_limit"

[search.frontier.models.time_limit]
time = 40.0
time_unit = "minutes"

[[search.frontier.models]]
type = "multimodal"
this_mode = "transit"
constraints = []
available_modes = [
    "walk",
    "transit",
]
route_ids_input_file = "boulder_co/transit/fq-route-ids-enumerated.txt.gz"
max_trip_legs = 5

[[plugin.input_plugins]]
extent_format = "wkt"
type = "grid"

[plugin.input_plugins.grid]
resolution = 8
type = "h3"

[[plugin.input_plugins]]
format = "key_value"
key = "mode"
type = "inject"
value = "walk"
write_mode = "overwrite"

[[plugin.input_plugins]]
format = "key_value"
key = "start_datetime"
type = "inject"
value = "2025-09-01 09:00:00"
write_mode = "overwrite"

[[plugin.output_plugins]]
tree = "geo_json"
type = "traversal"

[[plugin.output_plugins]]
type = "summary"

[[plugin.output_plugins]]
isochrone_output_format = "wkb"
type = "isochrone"

[plugin.output_plugins.destination_point_generator]
type = "destination_point"

[plugin.output_plugins.isochrone_algorithm]
k = 3
type = "k_nearest_concave_hull"

[plugin.output_plugins.time_bin]
times = [
    10,
    20,
    30,
    40,
]
type = "list"

[[plugin.output_plugins]]
collect_format = "aggregate"
type = "opportunity"

[plugin.output_plugins.model]
type = "combined"

[[plugin.output_plugins.model.models]]
activity_column_names = [
    "entertainment",
    "food",
    "retail",
    "healthcare",
    "services",
    "jobs",
]
table_orientation = "destination_vertex_oriented"
type = "api"
vertex_input_file = "boulder_co/vertices-compass.csv.gz"

[plugin.output_plugins.model.models.opportunity_source]
data_granularity = "census_tract"
edition = "LODES8"
job_type = "JT00"
segment = "S000"
type = "lodes"
year = 2022

[plugin.output_plugins.model.models.opportunity_source.activity_mapping]
CNS01 = ["jobs"]
CNS02 = ["jobs"]
CNS03 = ["jobs"]
CNS04 = ["jobs"]
CNS05 = ["jobs"]
CNS06 = ["jobs"]
CNS07 = [
    "jobs",
    "retail",
]
CNS08 = ["jobs"]
CNS09 = ["jobs"]
CNS10 = ["jobs"]
CNS11 = ["jobs"]
CNS12 = [
    "jobs",
    "services",
]
CNS13 = ["jobs"]
CNS14 = ["jobs"]
CNS15 = ["jobs"]
CNS16 = [
    "jobs",
    "healthcare",
]
CNS17 = [
    "jobs",
    "entertainment",
]
CNS18 = [
    "jobs",
    "food",
]
CNS19 = ["jobs"]
CNS20 = ["jobs"]

[plugin.output_plugins.model.models.opportunity_source.study_region]
geoids = ["08"]
type = "census"

[termination]
limit = 200000
type = "solution_size"

[system]
parallelism = 1
response_persistence_policy = "persist_response_in_memory"

[system.response_output_policy]
type = "combined"

[[system.response_output_policy.policies]]
type = "file"
filename = "result.json"

[system.response_output_policy.policies.format]
type = "json"
newline_delimited = false

[[system.response_output_policy.policies]]
type = "file"
filename = "result.csv"

[system.response_output_policy.policies.format]
type = "csv"
sorted = true

[system.response_output_policy.policies.format.mapping]
error = "error"
grid_id = "request.grid_id"
isochrone_10 = "bin.10.isochrone"
isochrone_20 = "bin.20.isochrone"
isochrone_30 = "bin.30.isochrone"
isochrone_40 = "bin.40.isochrone"
lat = "request.origin_y"
lon = "request.origin_x"
mode = "request.mode"
opps_entertainment_10 = "bin.10.opportunities.entertainment"
opps_entertainment_20 = "bin.20.opportunities.entertainment"
opps_entertainment_30 = "bin.30.opportunities.entertainment"
opps_entertainment_40 = "bin.40.opportunities.entertainment"
opps_entertainment_total = "opportunity_totals.entertainment"
opps_food_10 = "bin.10.opportunities.food"
opps_food_20 = "bin.20.opportunities.food"
opps_food_30 = "bin.30.opportunities.food"
opps_food_40 = "bin.40.opportunities.food"
opps_food_total = "opportunity_totals.food"
opps_healthcare_10 = "bin.10.opportunities.healthcare"
opps_healthcare_20 = "bin.20.opportunities.healthcare"
opps_healthcare_30 = "bin.30.opportunities.healthcare"
opps_healthcare_40 = "bin.40.opportunities.healthcare"
opps_healthcare_total = "opportunity_totals.healthcare"
opps_jobs_10 = "bin.10.opportunities.jobs"
opps_jobs_20 = "bin.20.opportunities.jobs"
opps_jobs_30 = "bin.30.opportunities.jobs"
opps_jobs_40 = "bin.40.opportunities.jobs"
opps_jobs_total = "opportunity_totals.jobs"
opps_retail_10 = "bin.10.opportunities.retail"
opps_retail_20 = "bin.20.opportunities.retail"
opps_retail_30 = "bin.30.opportunities.retail"
opps_retail_40 = "bin.40.opportunities.retail"
opps_retail_total = "opportunity_totals.retail"
opps_services_10 = "bin.10.opportunities.services"
opps_services_20 = "bin.20.opportunities.services"
opps_services_30 = "bin.30.opportunities.services"
opps_services_40 = "bin.40.opportunities.services"
opps_services_total = "opportunity_totals.services"
ram_mb = "search_result_size_mib"
runtime = "search_runtime"
